version: '2'
services:
  app:
    container_name: app-rails
    build: ./app/
    ports:
      - '80:80'
    volumes:
      - ~/share_space:/var/www/app/
    tty: true
    depends_on:
      - db
  db:
    container_name: mysql-57
    build: ./mysql/
    ports:
      - '3308:3306'
    environment:
      MYSQL_DATABASE: share_space
      MYSQL_ROOT_PASSWORD: password
      TZ: "Asia/Tokyo"
    volumes:
      - ./mysql/db_data:/var/lib/mysql
