version: '3'
services:
  app:
    build:
      context: .
    env_file:
      - ./environments/db.env
    command: bundle exec puma -C config/puma.rb
    volumes:
      - .:/share_space
      - public-data:/share_space/public
      - tmp-data:/share_space/tmp
      - log-data:/share_space/log
    depends_on:
      - db
  db:
    image: mysql:8.0
    env_file:
      - ./environments/db.env
    volumes:
      - db-data:/var/lib/mysql
  web:
    build:
      context: containers/nginx
    volumes:
      - public-data:/share_space/public
      - tmp-data:/share_space/tmp
    ports:
      - 80:80
    depends_on:
      - app
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    logging:
      driver: none

volumes:
  public-data:
  tmp-data:
  log-data:
  db-data:
